In [1]:
import pandas as pd

C:\Users\Asus\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
df = pd.read_csv('water_pollution_disease.csv')

In [3]:
df.head()

,Country,Region,Year,Water Source Type,Contaminant Level (ppm),pH Level,Turbidity (NTU),Dissolved Oxygen (mg/L),Nitrate Level (mg/L),Lead Concentration (µg/L),...,"Cholera Cases per 100,000 people","Typhoid Cases per 100,000 people","Infant Mortality Rate (per 1,000 live births)",GDP per Capita (USD),Healthcare Access Index (0-100),Urbanization Rate (%),Sanitation Coverage (% of Population),Rainfall (mm per year),Temperature (°C),Population Density (people per km²)
0,Mexico,North,2015,Lake,6.06,7.12,3.93,4.28,8.28,7.89,...,33,44,76.16,57057,96.92,84.61,63.23,2800,4.94,593
1,Brazil,West,2017,Well,5.24,7.84,4.79,3.86,15.74,14.68,...,27,8,77.30,17220,84.73,73.37,29.12,1572,16.93,234
2,Indonesia,Central,2022,Pond,0.24,6.43,0.79,3.42,36.67,9.96,...,39,50,48.45,86022,58.37,72.86,93.56,2074,21.73,57
3,Nigeria,East,2016,Well,7.91,6.71,1.96,3.12,36.92,6.77,...,33,13,95.66,31166,39.07,71.07,94.25,937,3.79,555
4,Mexico,South,2005,Well,0.12,8.16,4.22,9.15,49.35,12.51,...,31,68,58.78,25661,23.03,55.55,69.23,2295,31.44,414

In [5]:
df.columns

Index(['Country', 'Region', 'Year', 'Water Source Type',
       'Contaminant Level (ppm)', 'pH Level', 'Turbidity (NTU)',
       'Dissolved Oxygen (mg/L)', 'Nitrate Level (mg/L)',
       'Lead Concentration (µg/L)', 'Bacteria Count (CFU/mL)',
       'Water Treatment Method', 'Access to Clean Water (% of Population)',
       'Diarrheal Cases per 100,000 people',
       'Cholera Cases per 100,000 people', 'Typhoid Cases per 100,000 people',
       'Infant Mortality Rate (per 1,000 live births)', 'GDP per Capita (USD)',
       'Healthcare Access Index (0-100)', 'Urbanization Rate (%)',
       'Sanitation Coverage (% of Population)', 'Rainfall (mm per year)',
       'Temperature (°C)', 'Population Density (people per km²)'],
      dtype='str')

In [6]:
df.isna().sum()

Country                                            0
Region                                             0
Year                                               0
Water Source Type                                  0
Contaminant Level (ppm)                            0
pH Level                                           0
Turbidity (NTU)                                    0
Dissolved Oxygen (mg/L)                            0
Nitrate Level (mg/L)                               0
Lead Concentration (µg/L)                          0
Bacteria Count (CFU/mL)                            0
Water Treatment Method                           747
Access to Clean Water (% of Population)            0
Diarrheal Cases per 100,000 people                 0
Cholera Cases per 100,000 people                   0
Typhoid Cases per 100,000 people                   0
Infant Mortality Rate (per 1,000 live births)      0
GDP per Capita (USD)                               0
Healthcare Access Index (0-100)                    0
Urbanization Rate (%)                              0
Sanitation Coverage (% of Population)              0
Rainfall (mm per year)                             0
Temperature (°C)                                   0
Population Density (people per km²)                0
dtype: int64

In [9]:
df["Water Treatment Method"]=df["Water Treatment Method"].fillna(df["Water Source Type"].mode()[0])

In [11]:
df.isna().sum()
df.dtypes

Country                                              str
Region                                               str
Year                                               int64
Water Source Type                                    str
Contaminant Level (ppm)                          float64
pH Level                                         float64
Turbidity (NTU)                                  float64
Dissolved Oxygen (mg/L)                          float64
Nitrate Level (mg/L)                             float64
Lead Concentration (µg/L)                        float64
Bacteria Count (CFU/mL)                            int64
Water Treatment Method                               str
Access to Clean Water (% of Population)          float64
Diarrheal Cases per 100,000 people                 int64
Cholera Cases per 100,000 people                   int64
Typhoid Cases per 100,000 people                   int64
Infant Mortality Rate (per 1,000 live births)    float64
GDP per Capita (USD)                               int64
Healthcare Access Index (0-100)                  float64
Urbanization Rate (%)                            float64
Sanitation Coverage (% of Population)            float64
Rainfall (mm per year)                             int64
Temperature (°C)                                 float64
Population Density (people per km²)                int64
dtype: object

In [28]:

#encode the sreing value to numeric
from sklearn.preprocessing import LabelEncoder

le_country = LabelEncoder()
le_region  = LabelEncoder()
le_source  = LabelEncoder()
le_treat   = LabelEncoder()

df['Country']              = le_country.fit_transform(df['Country'])
df['Region']               = le_region.fit_transform(df['Region'])
df['Water Source Type']    = le_source.fit_transform(df['Water Source Type'])
df['Water Treatment Method'] = le_treat.fit_transform(df['Water Treatment Method'])

# now print the mappings
print("COUNTRY mapping:")
print(dict(zip(le_country.classes_, le_country.transform(le_country.classes_))))

print("\nREGION mapping:")
print(dict(zip(le_region.classes_, le_region.transform(le_region.classes_))))

print("\nWATER SOURCE mapping:")
print(dict(zip(le_source.classes_, le_source.transform(le_source.classes_))))

print("\nTREATMENT mapping:")
print(dict(zip(le_treat.classes_, le_treat.transform(le_treat.classes_))))

COUNTRY mapping:
{np.int64(0): np.int64(0), np.int64(1): np.int64(1), np.int64(2): np.int64(2), np.int64(3): np.int64(3), np.int64(4): np.int64(4), np.int64(5): np.int64(5), np.int64(6): np.int64(6), np.int64(7): np.int64(7), np.int64(8): np.int64(8), np.int64(9): np.int64(9)}

REGION mapping:
{np.int64(0): np.int64(0), np.int64(1): np.int64(1), np.int64(2): np.int64(2), np.int64(3): np.int64(3), np.int64(4): np.int64(4)}

WATER SOURCE mapping:
{np.int64(0): np.int64(0), np.int64(1): np.int64(1), np.int64(2): np.int64(2), np.int64(3): np.int64(3), np.int64(4): np.int64(4), np.int64(5): np.int64(5)}

TREATMENT mapping:
{np.int64(0): np.int64(0), np.int64(1): np.int64(1), np.int64(2): np.int64(2), np.int64(3): np.int64(3)}

In [30]:
df.head()

,Country,Region,Year,Water Source Type,Contaminant Level (ppm),pH Level,Turbidity (NTU),Dissolved Oxygen (mg/L),Nitrate Level (mg/L),Lead Concentration (µg/L),...,"Cholera Cases per 100,000 people","Typhoid Cases per 100,000 people","Infant Mortality Rate (per 1,000 live births)",GDP per Capita (USD),Healthcare Access Index (0-100),Urbanization Rate (%),Sanitation Coverage (% of Population),Rainfall (mm per year),Temperature (°C),Population Density (people per km²)
0,6,2,2015,0,6.06,7.12,3.93,4.28,8.28,7.89,...,33,44,76.16,57057,96.92,84.61,63.23,2800,4.94,593
1,1,4,2017,5,5.24,7.84,4.79,3.86,15.74,14.68,...,27,8,77.30,17220,84.73,73.37,29.12,1572,16.93,234
2,5,0,2022,1,0.24,6.43,0.79,3.42,36.67,9.96,...,39,50,48.45,86022,58.37,72.86,93.56,2074,21.73,57
3,7,1,2016,5,7.91,6.71,1.96,3.12,36.92,6.77,...,33,13,95.66,31166,39.07,71.07,94.25,937,3.79,555
4,6,3,2005,5,0.12,8.16,4.22,9.15,49.35,12.51,...,31,68,58.78,25661,23.03,55.55,69.23,2295,31.44,414

In [31]:
#divide the data
# ---> x train is data that use to as input. already given to model
# ---> y train is use as labeled output already given to the model 
# ---> x test is use as test data which model see first time after train from this data it 
# predict(unseen data)
# ---> y test is actual output and (output produced by (x test) data will compare)
from sklearn.model_selection import train_test_split

In [32]:
x=df.drop(["Diarrheal Cases per 100,000 people","Cholera Cases per 100,000 people","Typhoid Cases per 100,000 people","Infant Mortality Rate (per 1,000 live births)"],axis=1)
y=df[["Diarrheal Cases per 100,000 people","Cholera Cases per 100,000 people","Typhoid Cases per 100,000 people","Infant Mortality Rate (per 1,000 live births)"]]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print("Train data",x_train.shape)
print("test data",x_test.shape)

Train data (2400, 20)
test data (600, 20)

In [33]:
from sklearn.metrics import cohen_kappa_score,classification_report,accuracy_score,roc_auc_score,roc_curve,confusion_matrix

In [ ]:

#it is regression so function changed. classification function will diffrent
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

def evaluate_model(y_test, y_pred):
    names = ['Diarrheal', 'Cholera', 'Typhoid', 'Infant Mortality']
    
    for i, name in enumerate(names):
        r2   = r2_score(y_test.iloc[:, i], y_pred[:, i])
        mae  = mean_absolute_error(y_test.iloc[:, i], y_pred[:, i])
        rmse = np.sqrt(mean_squared_error(y_test.iloc[:, i], y_pred[:, i]))
        print(f"{name} => R²: {r2:.2f}  MAE: {mae:.2f}  RMSE: {rmse:.2f}")

In [35]:
#Scale (needed for SVR and KNN) vecause they have MultiOutputRegressor so we need to scale
scaler = StandardScaler()
x_train_sc = scaler.fit_transform(x_train)
x_test_sc  = scaler.transform(x_test)

"""
fit_transform  →  scaler LOOKS at the data, learns min/max/mean
                  then scales it
                  ✅ use ONLY on training data

transform      →  scaler DOESN'T look, just applies what it learned
                  ✅ use on test data

fit_transform on test data = WRONG ❌
                  because test data is "unseen"
                  if scaler looks at it, you are cheating!

"""

"""
ex:::  Think of it like an exam:

Training data = practice questions
→ fit_transform  (study from these, learn the pattern)

Test data = real exam
→ transform only  (apply what you learned, don't study the exam paper!)"""

"\nex:::  Think of it like an exam:\n\nTraining data = practice questions\n→ fit_transform  (study from these, learn the pattern)\n\nTest data = real exam\n→ transform only  (apply what you learned, don't study the exam paper!)"

In [36]:
# Linear Regression
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(x_train_sc, y_train)
y_pred_lr = lr.predict(x_test_sc)

print("LINEAR REGRESSION")
evaluate_model(y_test, y_pred_lr)

LINEAR REGRESSION
Diarrheal => R²: -0.01  MAE: 127.65  RMSE: 146.55
Cholera => R²: 0.00  MAE: 12.38  RMSE: 14.34
Typhoid => R²: -0.02  MAE: 25.47  RMSE: 29.25
Infant Mortality => R²: -0.02  MAE: 24.48  RMSE: 28.25

In [37]:
#  Decision Tree
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(max_depth=6, random_state=42)
dt.fit(x_train, y_train)
y_pred_dt = dt.predict(x_test)

print("DECISION TREE")
evaluate_model(y_test, y_pred_dt)

DECISION TREE
Diarrheal => R²: -0.14  MAE: 134.19  RMSE: 155.63
Cholera => R²: -0.04  MAE: 12.67  RMSE: 14.60
Typhoid => R²: -0.01  MAE: 25.34  RMSE: 29.10
Infant Mortality => R²: -0.04  MAE: 24.57  RMSE: 28.52

In [38]:
#  Random Forest
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(x_train, y_train)
y_pred_rf = rf.predict(x_test)

print("RANDOM FOREST")
evaluate_model(y_test, y_pred_rf)

RANDOM FOREST
Diarrheal => R²: -0.05  MAE: 129.79  RMSE: 149.33
Cholera => R²: -0.01  MAE: 12.45  RMSE: 14.44
Typhoid => R²: -0.01  MAE: 25.31  RMSE: 29.07
Infant Mortality => R²: -0.02  MAE: 24.41  RMSE: 28.21

In [39]:
#  SVR
from sklearn.svm import SVR
from sklearn.multioutput import MultiOutputRegressor

svr = MultiOutputRegressor(SVR(kernel='rbf'))
svr.fit(x_train_sc, y_train)
y_pred_svr = svr.predict(x_test_sc)

print("SVR")
evaluate_model(y_test, y_pred_svr)

SVR
Diarrheal => R²: -0.00  MAE: 127.39  RMSE: 146.00
Cholera => R²: 0.00  MAE: 12.36  RMSE: 14.32
Typhoid => R²: -0.02  MAE: 25.47  RMSE: 29.27
Infant Mortality => R²: -0.03  MAE: 24.57  RMSE: 28.33

In [40]:
# KNN
from sklearn.neighbors import KNeighborsRegressor

knn = MultiOutputRegressor(KNeighborsRegressor(n_neighbors=5))
knn.fit(x_train_sc, y_train)
y_pred_knn = knn.predict(x_test_sc)

print("KNN")
evaluate_model(y_test, y_pred_knn)

KNN
Diarrheal => R²: -0.25  MAE: 138.65  RMSE: 162.84
Cholera => R²: -0.18  MAE: 13.09  RMSE: 15.61
Typhoid => R²: -0.17  MAE: 26.44  RMSE: 31.32
Infant Mortality => R²: -0.19  MAE: 25.84  RMSE: 30.53

In [41]:
#save the best model(Linear Regression is best here)
#pickle is python tools help to save the object  to file.
#here we need to save model object into file
import pickle

#save the linear regression model
#with open:- open file
# Linear_reg_model_for_disease_water.pkl:- file name
# wb:- Write in binary mode (for saving)
#as f:- indicate this file as 'f'
# pickle.dump(lr,f):- Saves the lr model into file f
with open('Linear_reg_model_for_disease_water.pkl','wb') as f:
    pickle.dump(lr,f)


#Save the scaler. used to normalized input data. reduce the complexity
with open('scaler.pkl','wb') as f:
    pickle.dump(scaler,f)

print("Model save")

Model save